// settle — on-chain/off-chain boundary for the order book
//
// Turns a matched [`Trade`] into a broadcast on-chain atomic swap. The
// maker's order UTXO (a funded `order_book.simf` instance) is spent via the
// `Take` path: Input[0] = order UTXO, Output[0] = TAKER_AMOUNT of
// TAKER_ASSET to MAKER_SCRIPT_HASH, Output[1] = MAKER_AMOUNT of
// MAKER_ASSET to the taker's chosen destination.
//
// This is a thin coordinator over the smplx-sdk PSET builder. The actual
// witness/argument struct shapes are generated by `simplex build` into
// `crate::artifacts::order_book`; see `OrderBookProgram` and its
// `derived_order_book` module (expanded by `include_simf!`).

use simplex::constants::DUMMY_SIGNATURE;
use simplex::either::Left;
use simplex::transaction::{FinalTransaction, PartialInput, PartialOutput, ProgramInput, RequiredSignature, UTXO};

use crate::artifacts::order_book::OrderBookProgram;
use crate::artifacts::order_book::derived_order_book::{OrderBookArguments, OrderBookWitness};
use crate::offchain::core::client::ExchangeClient;
use crate::offchain::core::error::{Error, Result};
use crate::offchain::matching::order::Order;

/// Receipt for a settled take: the broadcast txid and the two output amounts.
#[derive(Debug, Clone)]
pub struct SettleReceipt {
    pub txid: String,
    pub maker_received: u64,
    pub taker_received: u64,
}

/// Build + sign + broadcast the Take transaction for a matched order.
///
/// Caller supplies:
///   - `client`: the exchange operator's signer+provider (for the taker
///     funding input and broadcast).
///   - `order`: the maker order being taken (carries the baked param set).
///   - `order_utxo`: the funded contract UTXO.
///   - `taker_dest_script`: the script the taker wants MAKER_ASSET sent to.
///
/// # Errors
/// Returns [`Error`] on provider/signer/program failure.
pub fn settle_take(
    client: &ExchangeClient,
    order: &Order,
    order_utxo: &UTXO,
    taker_dest_script: simplex::simplicityhl::elements::Script,
) -> Result<SettleReceipt> {
    // Compile the order's contract with its baked param set.
    let arguments = build_order_arguments(order);
    let program = OrderBookProgram::new(arguments);
    let program_script = program.get_script_pubkey(client.provider().get_network());

    // Sanity: the order UTXO must be the contract's.
    if order_utxo.txout.script_pubkey != program_script {
        return Err(Error::Settlement(format!(
            "order UTXO script does not match compiled contract for order {}",
            order.id
        )));
    }

    // Assemble the take transaction.
    let mut ft = FinalTransaction::new();

    // Input[0]: the maker's order UTXO, spent by the Simplicity program (Take path).
    let witness = build_take_witness();
    ft.add_program_input(
        PartialInput::new(order_utxo.clone()),
        ProgramInput::new(
            Box::new(program.as_ref().clone()),
            Box::new(witness),
        ),
        RequiredSignature::None,
    );

    // Output[0]: maker paid — TAKER_AMOUNT of TAKER_ASSET to MAKER_SCRIPT_HASH.
    // The covenant checks `output_script_hash(0) == param::MAKER_SCRIPT_HASH`,
    // so the script here must hash to the baked value. v1 uses an OP_RETURN
    // carrying the hash (see `script_from_hash`); production should resolve
    // the maker's actual script (e.g. P2TR whose script-hash matches).
    let maker_script = script_from_hash(order.maker_script_hash);
    ft.add_output(PartialOutput::new(
        maker_script,
        order.taker_amount,
        order.taker_asset,
    ));

    // Output[1]: taker receives MAKER_AMOUNT of MAKER_ASSET to free destination.
    ft.add_output(PartialOutput::new(
        taker_dest_script,
        order.maker_amount,
        order.maker_asset,
    ));

    let receipt = client.broadcast(&ft)?;
    Ok(SettleReceipt {
        txid: receipt.txid().to_string(),
        maker_received: order.taker_amount,
        taker_received: order.maker_amount,
    })
}

/// Construct the generated `OrderBookArguments` struct from an [`Order`].
///
/// Field names mirror the `param::` declarations lowercased:
///   MAKER_ASSET_ID → maker_asset_id: [u8; 32]
///   MAKER_AMOUNT   → maker_amount: u64
///   TAKER_ASSET_ID → taker_asset_id: [u8; 32]
///   TAKER_AMOUNT   → taker_amount: u64
///   MAKER_SCRIPT_HASH → maker_script_hash: [u8; 32]
///   MAKER_PUBKEY   → maker_pubkey: [u8; 32]
///   EXPIRY         → expiry: u32
///
/// Type mapping verified from simplicity-contracts/.../programs/option_offer.rs:
/// `AssetId::into_inner().0` → `[u8; 32]`; `XOnlyPublicKey::serialize()` →
/// `[u8; 32]`; `Time` → `u32`.
fn build_order_arguments(order: &Order) -> OrderBookArguments {
    OrderBookArguments {
        maker_asset_id: order.maker_asset.into_inner().0,
        maker_amount: order.maker_amount,
        taker_asset_id: order.taker_asset.into_inner().0,
        taker_amount: order.taker_amount,
        maker_script_hash: order.maker_script_hash,
        maker_pubkey: order.maker_pubkey,
        expiry: order.expiry,
    }
}

/// Construct the generated `OrderBookWitness` for the Take path (Left branch).
///
/// `witness::PATH` is `Either<(), ()>` — Take = `Left(())`, Cancel = `Right(())`.
/// `witness::MAKER_SIGNATURE` is `[u8; 64]` (unused on the Take path, so the
/// dummy signature is used, per the option_offer reference pattern).
fn build_take_witness() -> OrderBookWitness {
    OrderBookWitness {
        path: Left(()),
        maker_signature: DUMMY_SIGNATURE,
    }
}

/// Resolve a script whose hash equals the given 32-byte hash.
///
/// v1: emit an OP_RETURN carrying the hash so the covenant's
/// `output_script_hash(0) == param::MAKER_SCRIPT_HASH` check is satisfiable
/// in tests. Production should resolve the maker's actual script (e.g. a
/// P2TR output whose script-hash matches the baked value).
fn script_from_hash(hash: [u8; 32]) -> simplex::simplicityhl::elements::Script {
    simplex::simplicityhl::elements::Script::new_op_return(&hash)
}
